### ISSUE TITLE
Update aurelia-flux to support aurelia-framework 0.16

### ISSUE THREAD

**Issue by stevies** [tfrydrychewicz/aurelia-flux#14]
You can probably close https://github.com/tfrydrychewicz/aurelia-flux/issues/11 - requesting an update to framework 0.15.  We are now on 0.16.  And other dependencies have also been updated to newer versions.

**Comment by thomas-jakemeyn** [comment]
aurelia-flux is a great plugin. Can you please update its dependencies to the early September release of the Aurelia framework?

**Comment by thomas-jakemeyn** [comment]
As a temporary solution, you can use the fork I created: https://github.com/thomas-jakemeyn/aurelia-flux.

**Comment by stevies** [comment]
Thanks

**Comment by cdennig** [comment]
+1 please update to the current version of the Framework.

**Comment by stevies** [comment]
Please update work with aurelia-framework  0.17.0.  

I now get error like: 

```
Unhandled promise rejection TypeError: Cannot read property 'instance' of undefined
    at Function.interceptClassActivator (http://localhost:9000/myapp/frame/jspm_packages/github/tfrydrychewicz/aurelia-flux@0.1.7/lifecycle-manager.js:97:59)
    at a.configure (http://localhost:9000/myapp/frame/jspm_packages/github/tfrydrychewicz/aurelia-flux@0.1.7/index.js:12:44)
    at http://localhost:9000/myapp/frame/jspm_packages/github/aurelia/framework@0.17.0/aurelia-framework.js:34:34
    at f (http://localhost:9000/myapp/frame/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1415:56)
    at http://localhost:9000/myapp/frame/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1423:13
    at b.exports (http://localhost:9000/myapp/frame/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:453:24)
    at b.(anonymous function) (http://localhost:9000/myapp/frame/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1625:11)
    at Number.f (http://localhost:9000/myapp/frame/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1596:24)
    at q (http://localhost:9000/myapp/frame/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1600:11)
```

I realise the new aurelia version was released only yesterday, and that it may take some time for you to keep up-to-date.  

Thanks.
